sudo: required
dist: trusty
addons:
    artifacts: {paths: [results]}
    apt: {sources: [google-chrome], packages: [google-chrome-stable]}
language: node_js
node_js:
    - '7'
cache:
    directories: [node_modules, bower_components, $HOME/.npm, $HOME/.cache]
before_script:
    - 'npm install'
before_deploy:
    - 'npm run build'
env:
    global: [NODE_ENV=testing, ARTIFACTS_BUCKET=javascript-automation, {secure: VoLuBvgbRyrFZtIu7DYeT+hevWvJ5b8A36z9fBq4e+rBCfod2Sa/4N2j8wtlHAcitH3d71rQUiMWLLiCfZQY1IkC39d5h04uoeh67ytf1BeL5Zg2AUIJ/DDtM1rYvR5MgppvkLU3+JjHF3VhtAGdgX5zp2Ro8N+b9AVr7LfAytcYN4J/6OL9NYA3WFpRPFkZEED4x27oK9Shx5Yaf+LnFTzfQr09WsfzCxZyW31MA3CU/j47nzDhMkDAz7KIsI0/zCbo+Z6SbbhEhAG4UPYcw07QNLUUK+bMW7tySmn/CBUCYa0FA3vmSJf30a7rwQfHnhq54mjFlilGP0AK2mpCjHrQS4kGdIfr7OdW8ZwVqNDSpA7zMWcz+qj9BdMTDH9Xr/DKLDKkJxf9ZRbtNCqNsWCpFrXWYV1ychJtYtV143HVGMyimtDA8oesPJzqY3i1H/+KN23QdWXiFK09siETl+o7v4QKlDDz3nzLIpr9Ji0iXhsf5bF/uqyk10jabjmXTBMRMvMEj7iBHyBpt/drCB3Kj874O1aWjGQ2L/NwRLTnqiGXvuRieGFQ1AT+JYOP4dQtMq93Z19wpwuUANBWnhQWGrG35QQ7lm5/I1T2UNBIQM25Jzj83jFqxtz7iTwLZZYhuxeIWy3e2Y2iIJikV6iN2k2hvVxJjsst20pzBnM=}, {secure: peKzblpkrtOuHL1HIhUirZl/WRXAOOh0NWYJaWvIKL/bRJ3Z6IvruCdqt4uX6IsgVwU0kouBNkL1iWkkNB7lFPNJATicHQqZbaYn7xBmB9mbPtrbgZE9NxVCrEPwJhqO26BcdrGwBBmNgqaet/fqvev65EfAf40TSGppcI81O9Ik+jXhZonq/ssM1bhT97uphznkFSwS2Msu1NQ/+6/MyN4Ll4njFAvYIWjpl4HrrrvIprezIOak0RKwg/NMo/sq7RcmelX/1H0LbboYcdVVWIB+ehQE6CjSqVs0Gr92QYDiyJ0u6tX/5PNRERJX5MhRharbO3+7E0QO3LqTAhk8Xw10ztwEjnQe69gFzoYdgpsl44KaSQs+BJrHW/OZJgqEZvJCEqFXQp5Wklce+Ioc6NJZaS3IlM7EVuhaJcDptjyy3nuxJWStVdJUpKlZQONxxqJEyspzgZ6zBGnycupQGRbuMY/DliQl0VSxvdqRhUFfS7oU+troVon6JahumKx/Nm+gcQdR7Xfj1YALyP6+gkZ1BzdRGZ82zm/T+QKUZgq6u1la6NnmDvOR6asgGz1YqE+G592cgkBaMXGS6mjxggYCFWAOSuVKVFqvfiXzbUC52PtDmLu3I+XZQwlrRwnq9HWZ38WArNybxvbsr1xtWlD4X0Ij5+dS904RQHwRPMk=}]
script:
    - 'npm run test'
notifications:
    webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
